### ISSUE TITLE
Add field to ColdFront for tracking Institution - Specific Code

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#223]
## Motivation
We need to add a new field to ColdFront that users can add when they create a new project. They will also need to be able to modify it if their "Institution-specific code" changes. This code will help Institutions track internal PI or project codes.
the code can contain numbers and letters and "-". Max length 50 char.

Justin - Would this be better off as a feature upstream? Seems a bit out of scope for the coldfront-plugin-cloud repo and would be more broadly useful/applicable to all coldfront users regardless of the service(s) they allocate.

Krisiti - Upstream ColdFront doesn't have any invoicing features whereas we have started incorporating this kind of features into the plugin. Therefore it seems to make sense for now to keep putting those features there.

## Completion Criteria
able to add Institution - Specific Code to projects in Cold Front.

## Description
- [ ] Create Institution - Specific Code in Coldfront
   - max length 50 char
   - numbers and letters and "-"
- [ ] test that we can add Institution - Specific Code to project
- [ ] test that we can change Institution - Specific Code after a project is created
- [ ] test that we can add NA in the field

## Invoice Script
- OpenShift script will be updated [here](https://github.com/CCI-MOC/openshift-usage-scripts/issues/28)
- OpenStack script will be updated [here](https://github.com/CCI-MOC/openstack-billing-from-db/issues/28)

## Completion dates
Desired - 2023-12-22
Required - 2024-12-19

**Comment by knikolla** [comment]
Do want this on the Project, and for it to apply to all Resource Allocations of the Project? Or on each Resource Allocation itself?

**Comment by joachimweyl** [comment]
@Milstein Do we want `Institution - Specific Code` for each resource allocation or for it to apply to all resource allocations in a project?

**Comment by Milstein** [comment]
@knikolla @joachimweyl : Need to apply for all Resource Types.

**Comment by joachimweyl** [comment]
duplicate of https://github.com/nerc-project/coldfront-plugin-cloud/issues/129 merging in the next few min.
