### ISSUE TITLE
Create a Requirements Document for Lenovo A100 Usage tracking

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#307]
## Motivation
We need to be able to track the usage of the 64 Lenovo water-cooled A100s that we are leasing so that they can bill us for our usage of their A100s.

## Completion Criteria
The requirements are agreed upon by NERC & Lenovo. The requirements are checked into GH as markdown.

## Description
- [x] Create Google [doc](https://docs.google.com/document/d/1uzDcaothZS7tHj73_w6oRZxNmMsZPDsAEtf6UeGMcak/edit?usp=drive_link)
- [x] Flesh out Doc
- [x] Work with Engineers and Lenovo to update the doc
   - [x] OpenStack
   - [x] OpenShift
- [x] Sign-off from NERC
- [x] Sign-off from Lenovo

## OpenShift
```
$ oc get node wrk-95 -o yaml | grep -E '\s+nvidia.com/gpu.product'
    nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
```

## OpenStack
pci_name = a100-sxm4

## Completion dates
Desired - 2023-11-22
Required - TBD

**Comment by joachimweyl** [comment]
@msdisme now that we have the output for OpenShift the document has the steps of how we will be gathering usage. Shall we have NERC review doc first or Lenovo?

**Comment by joachimweyl** [comment]
@waygil @jtriley & @aabaris [here](https://docs.google.com/document/d/1uzDcaothZS7tHj73_w6oRZxNmMsZPDsAEtf6UeGMcak/edit?usp=drive_link) is the doc that we are using to share with Lenovo how we are tracking the usage of their GPUs.
