### ISSUE TITLE
Approval of new OBS cluster 1: Schedule first meeting with Harvard (Security) to discuss and agree on the Observabilty architecture

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#358]
After researching, drawing, and prototyping the observability cluster architecture ([Setup a new Cluster to handle Metrics, Logging and Observability](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQzNzMy)), the proposed solution needs to be presented to and finalized with Harvard.

Augustine was closely involved in the discussions and solution finding, but we need a final approve on this.

## Part 1 (this issue - Schedule first meeting with Harvard #358)
- https://github.com/nerc-project/operations/issues/358
- [X] first meeting (Jan 9th)
  - [X] diagrams approved
  - [X] logic and ideas approved (Grafana on obs, long term logs with victoria metrics, ...)
  - [X] recording & meeting notes

#### Expectations
1. not much changes compared to runbooks infra https://github.com/nerc-project/nerc-runbooks/blob/main/docs/nerc-ocp-infra-rebuild.md
2. creation of a runbook for obs
3. deliver data, store logs, make visible with test-cluster
4. J&A must be able to recreate by just using the new obs runbook (test case)

## Part 2 (Next meeting, prepare and show - demo & pov #406)
- https://github.com/nerc-project/operations/issues/406

## Part 3 (PoC done by J&A #407)
- https://github.com/nerc-project/operations/issues/407

## Part 4 (Approval & Close #408)
- https://github.com/nerc-project/operations/issues/408

**Comment by schwesig** [comment]
Meeting happened on Jan 9th
meeting was recorded, meeting notes exist
next steps in the top content

**Comment by schwesig** [comment]
working on obs rulebook & diff
