### ISSUE TITLE
Separate Resource Usage Reporting by Personas (Professor, Student, TA, RH)

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#396]
# Story
To enhance our resource management and gain insights into how resources are utilized, we would like to implement a system that allows us to generate separate usage reports for different user personas, including Professors, Students, Teaching Assistants (TAs), and RH.

# ToDo
- This issue is created to research already available options, and/or implement features for persona-based resource usage reporting.
  - [x] research already available options in NERC, RHOAI, ...
  - [x] research new options 
  - [x] activate available options/ implement new needed https://github.com/OCP-on-NERC/BU-RHOAI/issues/5

# Trigger
- https://github.com/OCP-on-NERC/BU-RHOAI/issues/4
- https://github.com/OCP-on-NERC/BU-RHOAI/issues/5

# could also be interesting for
- accounting

**Comment by schwesig** [comment]
https://github.com/OCP-on-NERC/BU-RHOAI/issues/5

**Comment by schwesig** [comment]
implementation in https://github.com/OCP-on-NERC/BU-RHOAI/issues/5
