### ISSUE TITLE
Request NESE allocation for NERC Test clusters

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#579]
## Motivation
We require 4 10 TB NESE allocations for 4 different clusters. Include Michael, Justin, Dylan, & Kim in the communications.

## Completion Criteria
4 10TB NESE allocations provided.

## Description
- [ ] Request 10TB allocation for [RHOAI test](https://github.com/nerc-project/operations/issues/419) cluster - Dylan
- [ ] Request 10TB allocation for [RHOAI Beta test](https://github.com/nerc-project/operations/issues/575) cluster - Dylan
- [ ] Request 10TB allocation for [OpenShift test](https://github.com/nerc-project/operations/issues/497) cluster - Steve
- [ ] Request 10TB allocation for [OpenShift Beta](https://github.com/nerc-project/operations/issues/518) test cluster - Dylan
- [ ] Request 10TB allocation for [Second OpenShift Test](https://github.com/CCI-MOC/ops-issues/issues/1318) Cluster - Taj

## Questions
1. which networks should be allowed to access these pools each?
1. Do you need three set key access: node, provisioner and healthchecker for each pool or just one per pool?
1. Who will be handling/receiving the access keys created for the pools?"

## Completion dates
Desired - 2024-05-29
Required - TBD

**Comment by joachimweyl** [comment]
@waygil let me know if you would prefer individual issues for each.

**Comment by waygil** [comment]
Are all of these request for triple replicated RBD pools?  This was how the recent Hypershift pool was set up.
One issue is fine as I'll make one request to NESE for this.

**Comment by joachimweyl** [comment]
Yes

**Comment by joachimweyl** [comment]
@waygil I have added the people responsible to each request above.

**Comment by waygil** [comment]
NESE ticket #003199 submitted:

_Hi Milan,

I hope the annual maintenance and NESE upgrades went well on your end.  A lot of work for sure, and we appreciate you and your teams efforts in running the NESE service!

I  would like to set up the following 4 10TB allocations for the Mass Open Cloud (MOC) :

1)	10TB allocation for the RHOAI test cluster called moc-rbd-rhoai-test (Dylan Stewart – [dystewar@redhat.com](mailto:dystewar@redhat.com))
2)	10TB allocation for the RHOAI Beta test cluster moc-rbd-rhoai-beta-test (Dylan Stewart – [dystewar@redhat.com](mailto:dystewar@redhat.com))
3)	10TB allocation for the OpenShift test cluster called moc-rbd-openshift-test (Steve Heckman – [sheckman@bu.edu](mailto:sheckman@bu.edu))
4)	10TB allocation for the OpenShift Beta cluster called moc-rbd-openshift-beta-test (Dylan Stewart – [dystewar@redhat.com](mailto:dystewar@redhat.com))

All of these will be RBD replicated allocations.  I’ve included the point people in this email (indicated in parentheses for each allocation) in case additional follow-up is needed on either side to get these set up.

If you would rather have individual support tickets for each request or require other initial information that you would like for these allocations, please let me know.

Thanks!

Wayne_

**Comment by waygil** [comment]
Added 5th request for 10TB covered under[ issue 1318](https://github.com/CCI-MOC/ops-issues/issues/1318#issuecomment-2155013773) and added Taj as a contact for that request.
-Wayne

**Comment by joachimweyl** [comment]
```
I've just created these 5 pools. I would need additional info about which networks should be allowed to access these pools each? Do you need three set key access: node, provisioner and healthchecker for each pool or just one per pool? Who will be handling/receiving the access keys created for the pools?

Milan
```

**Comment by joachimweyl** [comment]
[OSTicket#003199](https://mghpcc.supportsystem.com/scp/tickets.php?&number=003199)

**Comment by larsks** [comment]
I've posted the following update to the ticket:

> These are all openshift clusters, so they'll need the three auth principals (﻿node, provisioner and healthchecker) that we've used on other clusters. These clusters will all be deployed on the test subnet, ﻿VLAN 2175 (10.30.12.0/24).﻿﻿

**Comment by joachimweyl** [comment]
Milan responded "The keys have been created and sent out."

**Comment by joachimweyl** [comment]
@jtriley when you add the creds to vault please close this issue.

**Comment by jtriley** [comment]
@larsks @dystewart @tssala23 @joachimweyl external ceph configs for these cluster have been added to vault under the "nerc" secret engine using the cluster names for top-level "folder":

- [moc-rbd-rhoai-test](https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/secrets/nerc/kv/moc-rbd-rhoai-test%2Fopenshift-storage%2Frook-ceph-external-cluster-details/details?version=1)
- [moc-rbd-rhoai-beta-test](https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/secrets/nerc/kv/moc-rbd-rhoai-beta-test%2Fopenshift-storage%2Frook-ceph-external-cluster-details/details?version=1)
- [moc-rbd-openshift-test](https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/secrets/nerc/kv/moc-rbd-openshift-test%2Fopenshift-storage%2Frook-ceph-external-cluster-details/details?version=1)
- [moc-rbd-openshift-beta-test](https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/secrets/nerc/kv/moc-rbd-openshift-beta-test%2Fopenshift-storage%2Frook-ceph-external-cluster-details/details?version=1)
- [moc-rbd-openshift-test2](https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/secrets/nerc/kv/moc-rbd-openshift-test2%2Fopenshift-storage%2Frook-ceph-external-cluster-details/details?version=1)
