### ISSUE TITLE
Close out Epic once RHELAI requests are done

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#677]
## Motivation
don't loose track of closing out RHELAI epic.

## Completion Criteria
Once RHELAI is done we want to make sure to release all hardware and close the epic.

## Description
- [x] Wait for RHELAI to tell us they are done with the hardware
- [x] move hardware back
- [x] close out Epic

## Completion dates
Desired - 2024-09-11
Required - TBD

**Comment by joachimweyl** [comment]
@hpdempsey Do we know when RHELAI will be ready to release the last of the 4 GPU Nodes?

**Comment by joachimweyl** [comment]
to be released today
GA release complete

**Comment by joachimweyl** [comment]
`MOC-R8PAC23U31` handed back.
