### ISSUE TITLE
Close out InstructLab Epic once done with project

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#678]
## Motivation
don't lose track of closing out InstructLab epic.

## Completion Criteria
Once InstructLab is done we want to make sure to release all hardware and close the epic.

## Description
- [ ] Wait for InstructLab to tell us they are done with the hardware
- [ ] remove hardware access
- [ ] close out Epic

## Completion dates
Desired - 2024-09-11
Required - TBD
