### ISSUE TITLE
NERC Maintenance (Taint nerc-ocp-prod GPUs and add acceleratorProfiles) - Jan 14

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#849]
## Motivation
To prevent general non-GPU workloads from scheduling on nodes with GPUs we will be tainting the [nerc-ocp-prod](https://console.apps.shift.nerc.mghpcc.org/) GPU nodes. This is important because users are billed on a per host basis, so currently user workloads can be unintentionally scheduled on GPU nodes even when no GPU resources are allocated, resulting in being billed for GPU usage.  Additionally, this keeps the GPUs clear of all workloads not explicitly requesting GPU resources.
As a result of adding taints to the GPU nodes, we will also be adding accelerators to allow RHOAI users who have GPUs allocated, to select which tainted GPU they would like to land on (eg. A100 or V100). 

We will also fix the "None" acceleratorProfile behavior in: [issue](https://github.com/nerc-project/operations/issues/685)

## Completion Criteria
During the Jan 7 maintenance window, nerc-ocp-prod GPU nodes are tainted and acceleratorProfiles are added to the nerc-ocp-prod cluster RHOAI installation. 

## Description
- [x] RHOAI user docs updated to reflect accelerator selection (required before Jan 7) #852 
- [x] Taint nerc-ocp-prod GPU nodes tainted by GPU type (Jan 7) #846 
- [x] Add acceleratorProfiles to nerc-ocp-prod RHOAI (Jan 7) #847 
- [x] Fix None acceleratorProfile behavior (Jan 7) [PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/618)

## Completion dates
Required - 2025-01-07

**Comment by Milstein** [comment]
@here: Maintenance schedule is setup: https://nerc.instatus.com/cm4retg180022119ladrkl2t9
https://nerc.mghpcc.org/event/network-equipment-switch-maintenance-20250107/

Email announcement to all [NERC Users] is sent!

**Comment by joachimweyl** [comment]
@dystewart was this done yesterday?

**Comment by jtriley** [comment]
@joachimweyl I'm waiting on https://github.com/OCP-on-NERC/nerc-ocp-config/pull/536 to finish rolling out (machineconfig update that has to apply to every node in the cluster and involves reboots) and then I'm going to do the last piece of this issue (ie apply taints). I will close this issue when I'm done.
