### ISSUE TITLE
Make sure VM epic is for getting users on VM for OpenShift and not about Migration, move any migration issues over to another epic

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#863]
## Motivation
slit [epic](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTc4NTY0) out into 2 epics

## Completion Criteria
2 epics were created and all issues were divvied up between the two

## Description
- [ ] Create 1 new epic
   - VM migration 
- [ ] clean up old epic
   - VM testing
- [ ] move issues to new epic
- [ ] update roadmap accordingly
   - leave old epic where it is
   - move new epic to phase 1

## Completion dates
Desired - 2024-12-16
Required - 2024-12-20

**Comment by joachimweyl** [comment]
moved migration description and issues over to [OpenStack will no longer be supported and we need to migrate users to OpenShift VM](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMjE1Mjg0) epic
